// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Condiva.Api.Migrations
{
    [DbContext(typeof(CondivaDbContext))]
    [Migration("20260215154623_add_community_image_key")]
    partial class add_community_image_key
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AuthLibrary.Models.EmailVerifiedToken", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerifiedTokens");
                });

            modelBuilder.Entity("AuthLibrary.Models.ExternalAuthLogin", b =>
                {
                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Provider", "Subject");

                    b.HasIndex("UserId");

                    b.ToTable("ExternalAuthLogins");
                });

            modelBuilder.Entity("AuthLibrary.Models.PasswordResetToken", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("AuthLibrary.Models.RefreshToken", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Condiva.Api.Common.Auth.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImageKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Condiva.Api.Features.Communities.Models.Community", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnterCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnterCodeExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("Condiva.Api.Features.Events.Models.Event", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CommunityId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Condiva.Api.Features.Items.Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Condiva.Api.Features.Loans.Models.Loan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LenderUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnRequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerUserId");

                    b.HasIndex("CommunityId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LenderUserId");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.HasIndex("RequestId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("Condiva.Api.Features.Memberships.Models.Membership", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvitedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("UserId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("Condiva.Api.Features.Notifications.Models.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("EventId", "Type", "RecipientUserId")
                        .IsUnique();

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Condiva.Api.Features.Notifications.Models.NotificationDispatchState", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastProcessedEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationDispatchStates");
                });

            modelBuilder.Entity("Condiva.Api.Features.Notifications.Models.NotificationRule", b =>
                {
                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntityType", "Action", "Type");

                    b.ToTable("NotificationRuleMappings");
                });

            modelBuilder.Entity("Condiva.Api.Features.Offers.Models.Offer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("OffererUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OffererUserId");

                    b.HasIndex("RequestId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("Condiva.Api.Features.Reputations.Models.ReputationProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LendCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnTimeReturnCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReturnCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("UserId");

                    b.ToTable("Reputations");
                });

            modelBuilder.Entity("Condiva.Api.Features.Requests.Models.Request", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NeededFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NeededTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequesterUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("RequesterUserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("AuthLibrary.Models.EmailVerifiedToken", b =>
                {
                    b.HasOne("Condiva.Api.Common.Auth.Models.User", null)
                        .WithMany("EmailVerifiedTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuthLibrary.Models.ExternalAuthLogin", b =>
                {
                    b.HasOne("Condiva.Api.Common.Auth.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuthLibrary.Models.PasswordResetToken", b =>
                {
                    b.HasOne("Condiva.Api.Common.Auth.Models.User", null)
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuthLibrary.Models.RefreshToken", b =>
                {
                    b.HasOne("Condiva.Api.Common.Auth.Models.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Condiva.Api.Features.Events.Models.Event", b =>
                {
                    b.HasOne("Condiva.Api.Common.Auth.Models.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condiva.Api.Features.Communities.Models.Community", "Community")
                        .WithMany("Events")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("Condiva.Api.Features.Items.Models.Item", b =>
                {
                    b.HasOne("Condiva.Api.Features.Communities.Models.Community", "Community")
                        .WithMany("Items")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condiva.Api.Common.Auth.Models.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Condiva.Api.Features.Loans.Models.Loan", b =>
                {
                    b.HasOne("Condiva.Api.Common.Auth.Models.User", "BorrowerUser")
                        .WithMany()
                        .HasForeignKey("BorrowerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condiva.Api.Features.Communities.Models.Community", "Community")
                        .WithMany("Loans")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condiva.Api.Features.Items.Models.Item", "Item")
                        .WithMany("Loans")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condiva.Api.Common.Auth.Models.User", "LenderUser")
                        .WithMany()
                        .HasForeignKey("LenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condiva.Api.Features.Offers.Models.Offer", "Offer")
                        .WithOne("Loan")
                        .HasForeignKey("Condiva.Api.Features.Loans.Models.Loan", "OfferId");

                    b.HasOne("Condiva.Api.Features.Requests.Models.Request", "Request")
                        .WithMany("Loans")
                        .HasForeignKey("RequestId");

                    b.Navigation("BorrowerUser");

                    b.Navigation("Community");

                    b.Navigation("Item");

                    b.Navigation("LenderUser");

                    b.Navigation("Offer");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Condiva.Api.Features.Memberships.Models.Membership", b =>
                {
                    b.HasOne("Condiva.Api.Features.Communities.Models.Community", "Community")
                        .WithMany("Memberships")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condiva.Api.Common.Auth.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Condiva.Api.Features.Notifications.Models.Notification", b =>
                {
                    b.HasOne("Condiva.Api.Features.Communities.Models.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condiva.Api.Common.Auth.Models.User", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("Condiva.Api.Features.Offers.Models.Offer", b =>
                {
                    b.HasOne("Condiva.Api.Features.Communities.Models.Community", "Community")
                        .WithMany("Offers")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condiva.Api.Features.Items.Models.Item", "Item")
                        .WithMany("Offers")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condiva.Api.Common.Auth.Models.User", "OffererUser")
                        .WithMany()
                        .HasForeignKey("OffererUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condiva.Api.Features.Requests.Models.Request", "Request")
                        .WithMany("Offers")
                        .HasForeignKey("RequestId");

                    b.Navigation("Community");

                    b.Navigation("Item");

                    b.Navigation("OffererUser");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Condiva.Api.Features.Reputations.Models.ReputationProfile", b =>
                {
                    b.HasOne("Condiva.Api.Features.Communities.Models.Community", "Community")
                        .WithMany("Reputations")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condiva.Api.Common.Auth.Models.User", "User")
                        .WithMany("Reputations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Condiva.Api.Features.Requests.Models.Request", b =>
                {
                    b.HasOne("Condiva.Api.Features.Communities.Models.Community", "Community")
                        .WithMany("Requests")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Condiva.Api.Common.Auth.Models.User", "RequesterUser")
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("RequesterUser");
                });

            modelBuilder.Entity("Condiva.Api.Common.Auth.Models.User", b =>
                {
                    b.Navigation("EmailVerifiedTokens");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reputations");
                });

            modelBuilder.Entity("Condiva.Api.Features.Communities.Models.Community", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Items");

                    b.Navigation("Loans");

                    b.Navigation("Memberships");

                    b.Navigation("Offers");

                    b.Navigation("Reputations");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Condiva.Api.Features.Items.Models.Item", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Condiva.Api.Features.Offers.Models.Offer", b =>
                {
                    b.Navigation("Loan");
                });

            modelBuilder.Entity("Condiva.Api.Features.Requests.Models.Request", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
